# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ACCESui.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1591, 1456)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabGraphs = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabGraphs.sizePolicy().hasHeightForWidth())
        self.tabGraphs.setSizePolicy(sizePolicy)
        self.tabGraphs.setObjectName("tabGraphs")
        self.Graphs = QtWidgets.QWidget()
        self.Graphs.setObjectName("Graphs")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.Graphs)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.vsX = QtWidgets.QSlider(self.Graphs)
        self.vsX.setOrientation(QtCore.Qt.Vertical)
        self.vsX.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.vsX.setObjectName("vsX")
        self.verticalLayout.addWidget(self.vsX)
        self.lxset = QtWidgets.QLabel(self.Graphs)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.lxset.setFont(font)
        self.lxset.setObjectName("lxset")
        self.verticalLayout.addWidget(self.lxset)
        self.gridLayout_5.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.XData = PlotWidget(self.Graphs)
        self.XData.setObjectName("XData")
        self.gridLayout.addWidget(self.XData, 0, 0, 1, 1)
        self.lXData = QtWidgets.QLabel(self.Graphs)
        self.lXData.setObjectName("lXData")
        self.gridLayout.addWidget(self.lXData, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.vsY = QtWidgets.QSlider(self.Graphs)
        self.vsY.setOrientation(QtCore.Qt.Vertical)
        self.vsY.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.vsY.setObjectName("vsY")
        self.verticalLayout_2.addWidget(self.vsY)
        self.lyset = QtWidgets.QLabel(self.Graphs)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.lyset.setFont(font)
        self.lyset.setObjectName("lyset")
        self.verticalLayout_2.addWidget(self.lyset)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 2, 1)
        self.YData = PlotWidget(self.Graphs)
        self.YData.setObjectName("YData")
        self.gridLayout_3.addWidget(self.YData, 0, 1, 1, 1)
        self.lYData = QtWidgets.QLabel(self.Graphs)
        self.lYData.setObjectName("lYData")
        self.gridLayout_3.addWidget(self.lYData, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_5.addLayout(self.gridLayout_3, 1, 0, 1, 2)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.vsZ = QtWidgets.QSlider(self.Graphs)
        self.vsZ.setOrientation(QtCore.Qt.Vertical)
        self.vsZ.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.vsZ.setObjectName("vsZ")
        self.verticalLayout_3.addWidget(self.vsZ)
        self.lzset = QtWidgets.QLabel(self.Graphs)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.lzset.setFont(font)
        self.lzset.setObjectName("lzset")
        self.verticalLayout_3.addWidget(self.lzset)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 0, 0, 2, 1)
        self.ZData = PlotWidget(self.Graphs)
        self.ZData.setObjectName("ZData")
        self.gridLayout_4.addWidget(self.ZData, 0, 1, 1, 1)
        self.lZData = QtWidgets.QLabel(self.Graphs)
        self.lZData.setObjectName("lZData")
        self.gridLayout_4.addWidget(self.lZData, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_5.addLayout(self.gridLayout_4, 2, 0, 1, 2)
        self.tabGraphs.addTab(self.Graphs, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabGraphs.addTab(self.tab_2, "")
        self.gridLayout_2.addWidget(self.tabGraphs, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1591, 38))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabGraphs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "USB-AO16-16A"))
        self.lxset.setText(_translate("MainWindow", "000.0"))
        self.lXData.setText(_translate("MainWindow", "X-Position Data"))
        self.lyset.setText(_translate("MainWindow", "000.0"))
        self.lYData.setText(_translate("MainWindow", "Y-Position Data"))
        self.lzset.setText(_translate("MainWindow", "000.0"))
        self.lZData.setText(_translate("MainWindow", "Z-Position Data"))
        self.tabGraphs.setTabText(self.tabGraphs.indexOf(self.Graphs), _translate("MainWindow", "Graphs"))
        self.tabGraphs.setTabText(self.tabGraphs.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open Data File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))


from pyqtgraph import PlotWidget
